// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBquJdwMvKRVojgy2HLPCMzqhWi2wW7XTc',
    appId: '1:486419681133:web:0e71171d467ab76cacd464',
    messagingSenderId: '486419681133',
    projectId: 'my-broadcaad-app',
    authDomain: 'my-broadcaad-app.firebaseapp.com',
    storageBucket: 'my-broadcaad-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl63m8ScmlQ_-D5o_1n_rBhqxi9zwK_n8',
    appId: '1:486419681133:android:34cf2b2cd7ec387eacd464',
    messagingSenderId: '486419681133',
    projectId: 'my-broadcaad-app',
    storageBucket: 'my-broadcaad-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGpzfcWk3ds2WL7g6t-zE8i349OFS5Zzs',
    appId: '1:486419681133:ios:0c0ba7733ab6ac6facd464',
    messagingSenderId: '486419681133',
    projectId: 'my-broadcaad-app',
    storageBucket: 'my-broadcaad-app.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGpzfcWk3ds2WL7g6t-zE8i349OFS5Zzs',
    appId: '1:486419681133:ios:0c0ba7733ab6ac6facd464',
    messagingSenderId: '486419681133',
    projectId: 'my-broadcaad-app',
    storageBucket: 'my-broadcaad-app.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBquJdwMvKRVojgy2HLPCMzqhWi2wW7XTc',
    appId: '1:486419681133:web:67697524f2ae8a93acd464',
    messagingSenderId: '486419681133',
    projectId: 'my-broadcaad-app',
    authDomain: 'my-broadcaad-app.firebaseapp.com',
    storageBucket: 'my-broadcaad-app.appspot.com',
  );

}